#!/usr/bin/env bash

#Consider creating specialized git repositories as follows.

workingDir="$PWD"

# ATTENTION: Configure "$netName".
export netName=default
mkdir -p "$workingDir"/"$netName"
cd "$workingDir"/"$netName"

mkdir ./_lib
mkdir ./_prog

git init

# ATTENTION: Configure source.
# DANGER: Security software. Source must be explicitly configured.
#git submodule add --depth 1 git@github.com:mirage335/coreoracle.git ./_lib/coreoracle

git config -f .gitmodules submodule._lib/coreoracle.shallow true


#Parent derivative of ubiquitous_bash.
cd ./_lib/coreoracle
git submodule update --depth 1 --init ./_lib/ubiquitous_bash
cd ./_lib/ubiquitous_bash ; git fetch --shallow-exclude=v3.112 ; git reset --hard
cd "$workingDir"/"$netName"

#git submodule update --depth 1 --init --recursive

cp ./_lib/coreoracle/commKey ./
cp ./_lib/coreoracle/fragKey ./

cp ./_lib/coreoracle/compile.sh ./
cp ./_lib/coreoracle/license.txt ./
cp ./_lib/coreoracle/README.md ./

cp ./_lib/coreoracle/_lib/ubiquitous_bash/gpl-3.0.txt ./

##### Hardcoded Configuration
mkdir -p ./_config
cp -a ./_lib/coreoracle/_config/. ./_config
#cp -a ./_lib/coreoracle/_lib/ubiquitous_bash/_config/. ./_config

##### Parent Derivative Scripts
mkdir -p ./_prog
cp -a ./_lib/coreoracle/_prog/. ./_prog

##### Runtime Configuration
mkdir -p ./_local

#Parent derivative of ubiquitous_bash.
#cp ./_lib/coreoracle/_lib/ubiquitous_bash/_lib/coreoracle/ops ./_local/coreoracle/ops

#cp -a ./_lib/coreoracle/_local/. ./

##### Specialized project scripts.
cp ./_lib/coreoracle/upgrade ./
cp ./_lib/coreoracle/fork ./


./compile.sh

git add .
git commit -a -m "first commit"
