
# NOTICE: Strongly recommended to subsequently add autogenerated annotation to improve Retrieval-Augmented-Generation (RAG) with _semanticAssist .

_knowledge-coreoracle() {
    [[ "$objectName" != "coreoracle" ]] && _stop 1

    _safeRMR "$scriptLocal"/knowledge/coreoracle
    mkdir -p "$scriptLocal"/knowledge/coreoracle


    mkdir -p "$scriptLocal"/knowledge/coreoracle/_local
    cp -r "$scriptAbsoluteFolder"/_local/ops.sh "$scriptLocal"/knowledge/coreoracle/_local/
    cp -r "$scriptAbsoluteFolder"/fork "$scriptLocal"/knowledge/coreoracle/
    cp -r "$scriptAbsoluteFolder"/upgrade "$scriptLocal"/knowledge/coreoracle/


    mkdir -p "$scriptLocal"/knowledge/coreoracle/_lib
    #cp -r "$scriptAbsoluteFolder"/_lib/... "$scriptLocal"/knowledge/coreoracle/_lib/

    #cp -r "$scriptAbsoluteFolder"/_lib/_build-staging-ops.sh "$scriptLocal"/knowledge/coreoracle/_lib/

    cp -r "$scriptAbsoluteFolder"/_prog "$scriptLocal"/knowledge/coreoracle/
    rm -f "$scriptLocal"/knowledge/coreoracle/_prog/notices/_gather.sh

    #cp -r "$scriptAbsoluteFolder"/_prog-ops "$scriptLocal"/knowledge/coreoracle/

    #cp -r "$scriptAbsoluteFolder"/.devops "$scriptLocal"/knowledge/coreoracle/
    cp -r "$scriptAbsoluteFolder"/.github "$scriptLocal"/knowledge/coreoracle/

    #cp -r "$scriptAbsoluteFolder"/ops "$scriptLocal"/knowledge/coreoracle/

    #cp -r "$scriptAbsoluteFolder"/license-llama "$scriptLocal"/knowledge/coreoracle/
    #cp "$scriptAbsoluteFolder"/Notice.txt "$scriptLocal"/knowledge/coreoracle/
    cp "$scriptAbsoluteFolder"/license.txt "$scriptLocal"/knowledge/coreoracle/
    #cp "$scriptAbsoluteFolder"/license-installer.txt "$scriptLocal"/knowledge/coreoracle/
    #cp "$scriptAbsoluteFolder"/agpl-3.0.txt "$scriptLocal"/knowledge/coreoracle/
    cp "$scriptAbsoluteFolder"/gpl-3.0.txt "$scriptLocal"/knowledge/coreoracle/

    cp "$scriptAbsoluteFolder"/devtask.sh "$scriptLocal"/knowledge/coreoracle/

    cp "$scriptAbsoluteFolder"/_shortcuts-cygwin.sh "$scriptLocal"/knowledge/coreoracle/
    cp "$scriptAbsoluteFolder"/_shortcuts.sh "$scriptLocal"/knowledge/coreoracle/

    #cp "$scriptAbsoluteFolder"/bandKey "$scriptLocal"/knowledge/coreoracle/
    #cp "$scriptAbsoluteFolder"/commKey "$scriptLocal"/knowledge/coreoracle/
    #cp "$scriptAbsoluteFolder"/fragKey "$scriptLocal"/knowledge/coreoracle/
    #cp "$scriptAbsoluteFolder"/pairKey "$scriptLocal"/knowledge/coreoracle/
    #cp "$scriptAbsoluteFolder"/planKey "$scriptLocal"/knowledge/coreoracle/

    cp "$scriptAbsoluteFolder"/README.sh.out.txt "$scriptLocal"/knowledge/coreoracle/
    #cp "$scriptAbsoluteFolder"/README-installer.pdf "$scriptLocal"/knowledge/coreoracle/

    cp "$scriptAbsoluteFolder"/WARNING_cryptography_willBeREPORTED_and_publicNOTICES.txt "$scriptLocal"/knowledge/coreoracle/
}
