
# WARNING: May be untested .

name: test
on:
  push:
  workflow_dispatch:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    #- cron: '5 1 * * 6'
    #- cron: '5 1 * * 2,4'
    #- cron: '5 1 * * 2'
    #- cron: '5 1 * * 4'
    - cron: '5 1 * * 5'

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_latest-commKey:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04
    #runs-on: ubuntu-18.04
    steps:
      - name: _getCore_ub
        shell: bash
        timeout-minutes: 90
        run: |
          mkdir -p ~/core/infrastructure
          cd ~/core/infrastructure
          git clone --depth 1 --recursive https://github.com/mirage335/ubiquitous_bash.git
          cd ubiquitous_bash
          ./_setupUbiquitous.bat
      - name: _getMinimal_cloud
        shell: bash
        run: |
          ~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _getMinimal_cloud
        timeout-minutes: 90
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: _getMinimal_cloud
        shell: bash
        run: |
          ./_lib/ubiquitous_bash/ubiquitous_bash.sh _getMinimal_cloud
        timeout-minutes: 90
      - name: _setup
        shell: bash
        run: |
          ./commKey _setup
      - name: _query_search
        shell: bash
        run: |
          echo -n BASH_echo PASS | ./commKey _query_search | grep PASS
  test_latest-pairKey:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04
    #runs-on: ubuntu-18.04
    steps:
      - name: _getCore_ub
        shell: bash
        timeout-minutes: 90
        run: |
          mkdir -p ~/core/infrastructure
          cd ~/core/infrastructure
          git clone --depth 1 --recursive https://github.com/mirage335/ubiquitous_bash.git
          cd ubiquitous_bash
          ./_setupUbiquitous.bat
      - name: _getMinimal_cloud
        shell: bash
        run: |
          ~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _getMinimal_cloud
        timeout-minutes: 90
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: _getMinimal_cloud
        shell: bash
        run: |
          ./_lib/ubiquitous_bash/ubiquitous_bash.sh _getMinimal_cloud
        timeout-minutes: 90
      - name: _setup
        shell: bash
        run: |
          ./pairKey _setup
      - name: dummyPair
        shell: bash
        run: |
          dd if=/dev/urandom of="$HOME"/.pair bs=1M count=10 iflag=fullblock
          head -c 20 "$HOME"/.pair > "$HOME"/.pair-keyAuth
      - name: logTTY
        shell: bash
        run: |
          echo '_pair-logTTY() { cat > /dev/tty; }' > ./_local/ops
      - name: _pair-emit
        shell: bash
        run: |
          echo 'the quick brown fox jumps over the lazy dog' | ./pairKey _pair-emit | ./pairKey _pair-emit | ./pairKey _pair-emit | ./pairKey _pair-emit
      - name: _pair-emit PURE
        shell: bash
        run: |
          export FORCE_PURE=true ; echo 'the quick brown fox jumps over the lazy dog' | ./pairKey _pair-emit | ./pairKey _pair-emit | ./pairKey _pair-emit | ./pairKey _pair-emit
  test_latest-bandKey:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04
    #runs-on: ubuntu-18.04
    steps:
      - name: _getCore_ub
        shell: bash
        timeout-minutes: 90
        run: |
          mkdir -p ~/core/infrastructure
          cd ~/core/infrastructure
          git clone --depth 1 --recursive https://github.com/mirage335/ubiquitous_bash.git
          cd ubiquitous_bash
          ./_setupUbiquitous.bat
      - name: _getMinimal_cloud
        shell: bash
        run: |
          ~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _getMinimal_cloud
        timeout-minutes: 90
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: _getMinimal_cloud
        shell: bash
        run: |
          ./_lib/ubiquitous_bash/ubiquitous_bash.sh _getMinimal_cloud
        timeout-minutes: 90
      - name: _setup
        shell: bash
        run: |
          ./pairKey _setup
      - name: _pair-emit
        shell: bash
        run: |
          echo 'the quick brown fox jumps over the lazy dog' | ./bandKey _band | ./bandKey _band | ./bandKey _band | ./bandKey _band
      - name: _pair-emit PURE
        shell: bash
        run: |
          export FORCE_PURE=true ; echo 'the quick brown fox jumps over the lazy dog' | ./bandKey _band | ./bandKey _band | ./bandKey _band | ./bandKey _band

